//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://www.freesql.net
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using FreeSql.DataAnnotations;

    [JsonObject(MemberSerialization.OptIn)]
    public partial class AnswerQuestionnaire
    {

        [JsonProperty, Column(IsPrimary = true)]
        public long Id { get; set; }


        [JsonProperty, Column(DbType = "varchar(50)")]
        public string RecordId
        {
            get => _recordid;
            set
            {
                if (_recordid != value)
                {
                    _recordid = value;
                }
            }
        }
        private string _recordid;

        [JsonProperty]
        public short? TypeId
        {
            get => _typeid;
            set
            {
                if (_typeid != value)
                {
                    _typeid = value;
                }
            }
        }
        private short? _typeid;

        [JsonProperty]
        public DateTime CreateTime { get; set; }


        #region 外键 => 导航属性，ManyToOne/OneToOne


        [Navigate("RecordId, TypeId")]
        public virtual MedicalRecord MedicalRecord { get; set; }

        #endregion

        #region 外键 => 导航属性，ManyToMany

        #endregion
    }

