//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://www.freesql.net
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using FreeSql.DataAnnotations;

    [JsonObject(MemberSerialization.OptIn)]
    public partial class MedicalRecord
    {

        [JsonProperty, Column(DbType = "varchar(50)", IsPrimary = true)]
        public string RecordId { get; set; }

        [JsonProperty, Column(IsPrimary = true)]
        public short TypeId { get; set; }

        [JsonProperty]
        public DateTime? CreateTime { get; set; }

        [JsonProperty, Column(DbType = "decimal(9,2)")]
        public decimal InsuranceAmount { get; set; }

        [JsonProperty]
        public DateTime? LastModifyTime { get; set; }

        [JsonProperty, Column(DbType = "decimal(9,2)")]
        public decimal SelfAmount { get; set; }

        [JsonProperty, Column(DbType = "decimal(9,2)")]
        public decimal TotalAmount { get; set; }

        #region 外键 => 导航属性，OneToMany

        [Navigate("TypeId, RecordId")]
        public virtual List<AnswerQuestionnaire> AnswerQuestionnaires { get; set; }

        #endregion

        #region 外键 => 导航属性，ManyToMany

        #endregion
    }
