//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具 FreeSql.Generator 生成。
//     运行时版本:3.1.0
//     Website: https://github.com/2881099/FreeSql
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using FreeSql.DataAnnotations;
namespace FreeSql.Jhfw.Models {

    [JsonObject(MemberSerialization.OptIn), Table(Name = "banks")]
    public partial class Banks : IBaseModel<int>
    {

        [JsonProperty, Column(DbType = "datetime")]
        public DateTime? Addtime { get; set; }

        [JsonProperty, Column(DbType = "varchar(250)")]
        public string Banner { get; set; } = "";

        [JsonProperty, Column(DbType = "varchar(20)")]
        public string City { get; set; } = "";

        [JsonProperty, Column(Name = "ID", IsIdentity = true)]
        public int Id { get; set; }

        [JsonProperty, Column(DbType = "tinyint(1)")]
        public bool IsDelete { get; set; }

        [JsonProperty, Column(DbType = "tinyint(1)")]
        public bool IsGrab { get; set; }

        [JsonProperty, Column(DbType = "tinyint(1)")]
        public bool IsJoinHmd { get; set; }

        [JsonProperty, Column(DbType = "varchar(100)")]
        public string LoanType { get; set; } = "";

        [JsonProperty, Column(DbType = "varchar(250)")]
        public string Logo { get; set; } = "";

        [JsonProperty]
        public string Name { get; set; } = "";

        [JsonProperty, Column(DbType = "varchar(3000)")]
        public string Notice { get; set; } = "";


        #region 外键 => 导航属性，OneToMany

        [Navigate("BankId")]
        public virtual List<BankOutlets> ManyBankOutlets { get; set; }

        #endregion

        #region 外键 => 导航属性，ManyToMany

        #endregion
    }

}
